cloud:
  aws:
    credentials:
      access-key: ASIA6GBMFYI5JDN3LDQD
      secret-key: QOWOIiuJCayla6ezvdmYm5ygikxo18J/RDTnDptw
      session-token: IQoJb3JpZ2luX2VjEGIaCXVzLXdlc3QtMiJIMEYCIQDLWRxZgY+Cdx1gw1bF0gGQS78HFa6fQRa+OoemjErRYAIhAM/FubCphQR0Kpvav1xZ6Rj4Aficjy4VxRxcfnBKLSrWKq8CCNv//////////wEQABoMOTc1MDUwMjI4MjgyIgx2KDEMn4SQZDkOJ04qgwLsvxrI6+dOTMIYZi6pbo33l6pcdOaKoUn+RyqOAhw+Cls7+lPp2TMsqd07BEP6sWuwBwW2+tZESSEhnrdgiNgOpWsJ2O+mUhM2iwuNwofGCD2Pw9EaXDnuT2+5lPOocD/7ksTekVJx+7Mwk659/U26BcuBam6bXOveQex3Su7CngLn4YUsrGAFDotX8RCnH0yIyYZC+ZJSvH+4jjDI8O7Oj7WsG6QwFLU7hKiODqytpVJQWUYduMYKQbr1xwdyAvE1rz9KsERkoXgpLuNJPiS2nBfwvLGq70RmqDCTVk46Kwe6fLr9x5FGleK19y+R4mWLp0W6u6Klv6Yq4/om2VlMOMWpMPjknrkGOpwBicXatBmDLhuDxtudOFubn6/bSiSTF2BruMaKXDFETJ33o9r97XAola+i1GBUbILjRY7x3/cYamxJaJvC+eRE2crvrZcDwfmwhtpq1mYI9sCrTni+zBpK7+jzOdb9XBLbgUROmtT4uyvQ4nyKg7mgBMzwKOJx/VABZj3jg/ppd4v2sg8++VDH+rc9B29dIKFTwbpqef93WrVPB0dm
    region:
      static: us-east-1
    stack:
      auto: false